"""Briefings API — comprehensive research briefings.

Three generation modes, all producing complete output:
- basic: paper listings + stats (no LLM)
- ollama: paper listings + LLM analysis via local Ollama
- api: paper listings + LLM analysis via Anthropic/OpenAI API
- claude-code: paper listings + analysis generated by Claude Code agent in background
"""

from collections import Counter
from datetime import datetime

from fastapi import APIRouter, BackgroundTasks, Depends
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.deps import get_session
from packages.core.models import Item

router = APIRouter(prefix="/api/briefings", tags=["briefings"])

_briefings: list[dict] = []


@router.get("/")
async def list_briefings() -> dict:
    return {"briefings": _briefings}


@router.get("/{briefing_id}")
async def get_briefing(briefing_id: int) -> dict:
    if 0 <= briefing_id < len(_briefings):
        return _briefings[briefing_id]
    return {"error": "not found"}


class GenerateRequest(BaseModel):
    period: str = "daily"
    mode: str = "ollama"  # "basic", "ollama", "api", "claude-code"


@router.post("/generate")
async def generate_briefing(
    req: GenerateRequest,
    background_tasks: BackgroundTasks,
    session: AsyncSession = Depends(get_session),
) -> dict:
    result = await session.execute(
        select(Item).where(Item.relevance_score.isnot(None)).order_by(Item.relevance_score.desc()).limit(50)
    )
    items = result.scalars().all()
    if not items:
        return {"error": "No items with relevance scores. Run calibration first."}

    # Always build the base paper listing
    base_content = _generate_comprehensive_briefing(items, req.period)
    now = datetime.now()

    if req.mode == "basic":
        content = base_content
    elif req.mode == "ollama":
        content = await _generate_llm_analysis(items, req.period, base_content, None)
    elif req.mode == "api":
        model_override = _get_api_model()
        content = await _generate_llm_analysis(items, req.period, base_content, model_override)
    elif req.mode == "claude-code":
        # Background generation — returns immediately, UI polls for result
        briefing_id = len(_briefings)
        briefing = {
            "id": briefing_id,
            "period": req.period,
            "mode": "claude-code",
            "content": base_content,
            "created_at": now.isoformat(),
            "must_read_count": sum(1 for i in items if (i.relevance_score or 0) >= 0.7),
            "on_radar_count": sum(1 for i in items if 0.4 <= (i.relevance_score or 0) < 0.7),
            "generating": True,
        }
        _briefings.insert(0, briefing)
        # Fire background LLM task
        import asyncio
        asyncio.get_event_loop().create_task(
            _background_llm_analysis(briefing_id, items, req.period, base_content)
        )
        return briefing
    else:
        content = base_content

    briefing = {
        "id": len(_briefings),
        "period": req.period,
        "mode": req.mode,
        "content": content,
        "created_at": now.isoformat(),
        "must_read_count": sum(1 for i in items if (i.relevance_score or 0) >= 0.7),
        "on_radar_count": sum(1 for i in items if 0.4 <= (i.relevance_score or 0) < 0.7),
    }
    _briefings.insert(0, briefing)
    return briefing


class SaveBriefingRequest(BaseModel):
    content: str
    period: str = "daily"


@router.post("/save")
async def save_briefing(req: SaveBriefingRequest) -> dict:
    now = datetime.now()
    briefing = {
        "id": len(_briefings),
        "period": req.period,
        "mode": "claude-code",
        "content": req.content,
        "created_at": now.isoformat(),
        "must_read_count": 0,
        "on_radar_count": 0,
    }
    _briefings.insert(0, briefing)
    return briefing


# ---------------------------------------------------------------------------
# Generation backends
# ---------------------------------------------------------------------------

def _generate_comprehensive_briefing(items: list, period: str) -> str:
    """Paper listings, topics, authors, venues — no LLM needed."""
    now = datetime.now()
    must_read = [i for i in items if (i.relevance_score or 0) >= 0.7]
    on_radar = [i for i in items if 0.4 <= (i.relevance_score or 0) < 0.7]

    lines = [f"# {period.title()} Research Briefing", f"*{now.strftime('%B %d, %Y')}* — {len(must_read)} must-read, {len(on_radar)} on-radar\n"]

    if must_read:
        lines.append("## Must-Read Papers\n")
        for item in must_read[:15]:
            authors = ", ".join(item.authors[:3]) if isinstance(item.authors, list) and item.authors else "Unknown"
            extra = f" +{len(item.authors) - 3}" if isinstance(item.authors, list) and len(item.authors) > 3 else ""
            venue = item.venue or "Preprint"
            url = item.url or "#"
            pub = f" | {item.published_at.strftime('%b %Y')}" if item.published_at else ""
            lines.append(f"### [{item.title}]({url})")
            lines.append(f"**{authors}{extra}** — {venue}{pub} | Relevance: {item.relevance_score:.0%}")
            if item.summary:
                lines.append(f"\n{item.summary}")
            elif item.abstract:
                lines.append(f"\n{item.abstract[:200]}...")
            lines.append("")

    if on_radar:
        lines.append("## On the Radar\n")
        for item in on_radar[:15]:
            url = item.url or "#"
            desc = f" — {item.summary[:80]}..." if item.summary else ""
            lines.append(f"- [{item.title}]({url}) ({item.venue or 'Preprint'}, {item.relevance_score:.0%}){desc}")
        lines.append("")

    tag_counter: Counter = Counter()
    author_counter: Counter = Counter()
    venue_counter: Counter = Counter()
    for item in items:
        for tag in (item.tags if isinstance(item.tags, list) else []):
            if isinstance(tag, str) and tag:
                tag_counter[tag] += 1
        for author in (item.authors if isinstance(item.authors, list) else []):
            if isinstance(author, str) and author:
                author_counter[author] += 1
        if item.venue:
            venue_counter[item.venue] += 1

    if tag_counter:
        lines.append("## Emerging Topics\n")
        for tag, count in tag_counter.most_common(10):
            lines.append(f"- **{tag}** — {count} papers")
        lines.append("")
    if author_counter:
        lines.append("## Most Active Authors\n")
        for author, count in author_counter.most_common(10):
            if count >= 2:
                lines.append(f"- **{author}** — {count} papers")
        lines.append("")
    if venue_counter:
        lines.append("## Top Venues\n")
        for venue, count in venue_counter.most_common(8):
            if count >= 2:
                lines.append(f"- **{venue}** — {count} papers")
        lines.append("")

    return "\n".join(lines)


async def _generate_llm_analysis(items: list, period: str, base_content: str, model_override: str | None = None) -> str:
    """Base listing + LLM analysis. Works with Ollama or API models."""
    try:
        from packages.agents.llm import completion

        paper_context = _build_paper_context(items[:25])
        kwargs = {}
        if model_override:
            kwargs["model"] = model_override

        result = await completion(
            prompt=paper_context,
            system=DEEP_ANALYSIS_PROMPT,
            agent_name="briefing_writer",
            max_tokens=3000,
            **kwargs,
        )
        analysis = result.get("content", "")
        model_used = result.get("model", "unknown")
        return base_content + f"\n\n---\n*Analysis by {model_used}*\n\n{analysis}"

    except Exception as e:
        return base_content + f"\n\n---\n*LLM analysis failed: {e}*"


async def _background_llm_analysis(briefing_id: int, items: list, period: str, base_content: str) -> None:
    """Background: run LLM analysis and update the briefing in-place when done."""
    try:
        content = await _generate_llm_analysis(items, period, base_content, None)
        for b in _briefings:
            if b.get("id") == briefing_id:
                b["content"] = content
                b["generating"] = False
                break
    except Exception as e:
        for b in _briefings:
            if b.get("id") == briefing_id:
                b["content"] = base_content + f"\n\n---\n*Analysis failed: {e}*"
                b["generating"] = False
                break


async def _claude_code_generate(placeholder_id: int, base_content: str, item_data: list[dict], period: str) -> None:
    """Legacy background task."""
    try:
        from packages.agents.llm import completion

        paper_context = []
        for item in item_data[:25]:
            paper_context.append(
                f"- [{item['score']:.0%}] {item['title']}\n"
                f"  Authors: {', '.join(item['authors'][:3])} | Venue: {item['venue'] or 'Preprint'}\n"
                f"  Summary: {item.get('summary', 'N/A')}\n"
                f"  Abstract: {(item.get('abstract') or 'N/A')[:300]}"
            )

        result = await completion(
            prompt="\n".join(paper_context),
            system=DEEP_ANALYSIS_PROMPT,
            agent_name="briefing_writer",
            max_tokens=3000,
        )
        analysis = result.get("content", "")
        model_used = result.get("model", "Claude Code")

        # Update the placeholder in-place
        for b in _briefings:
            if b.get("id") == placeholder_id:
                b["content"] = base_content + f"\n\n---\n*Analysis by {model_used}*\n\n{analysis}"
                b.pop("status", None)
                break

    except Exception as e:
        for b in _briefings:
            if b.get("id") == placeholder_id:
                b["content"] = base_content + f"\n\n---\n*Claude Code analysis failed: {e}. The paper listings above are still complete.*"
                b.pop("status", None)
                break


def _build_paper_context(items: list) -> str:
    lines = []
    for item in items:
        abstract = (item.abstract or "")[:400]
        summary = item.summary or ""
        venue = item.venue or "unknown"
        authors = ", ".join(item.authors[:3]) if isinstance(item.authors, list) else ""
        pub = item.published_at.strftime("%b %Y") if item.published_at else "unknown date"
        lines.append(
            f"- [{item.relevance_score:.0%}] {item.title}\n"
            f"  Authors: {authors} | Venue: {venue} | Date: {pub}\n"
            f"  Summary: {summary}\n"
            f"  Abstract: {abstract}"
        )
    return "\n".join(lines)


def _serialize_items_for_analysis(items: list) -> list[dict]:
    return [
        {
            "title": i.title,
            "abstract": i.abstract[:500] if i.abstract else None,
            "authors": i.authors[:5] if isinstance(i.authors, list) else [],
            "venue": i.venue,
            "score": round(i.relevance_score or 0, 2),
            "summary": i.summary,
        }
        for i in items[:30]
    ]


def _get_api_model() -> str | None:
    """Read the API model from models.yaml — looks for anthropic or openai."""
    from pathlib import Path

    import yaml
    path = Path("config/models.yaml")
    if not path.exists():
        return None
    with open(path) as f:
        config = yaml.safe_load(f) or {}
    model = config.get("default", {}).get("model", "")
    # If currently ollama, try to find an API model in the config comments or fallback
    if model.startswith("ollama/"):
        return "anthropic/claude-haiku-4-5-20251001"
    return model


DEEP_ANALYSIS_PROMPT = """You are a research intelligence analyst. Given papers from a researcher's feed (with relevance scores, venues, dates, summaries, and abstracts), produce analysis sections. The paper listings are included separately — do NOT list papers again. Focus on ANALYSIS.

## Key Trends
3-5 trends. For each: what's accelerating, which specific papers show this, why it matters. Name the papers.

## Gaps & Research Opportunities
3-5 gaps. Each specific enough to become a paper. Ground each in what the papers say but don't solve.

## Research Paper Ideas
5 concrete ideas. For each:
- **Title**: realistic paper title
- **Key contribution**: 1-2 sentences
- **Target venue**: specific venue (RE, ICSE, NeurIPS, COLM, FSE, TOSEM, IEEE Software)
- **Why now**: what makes this timely
- **Grounding**: which 2-3 papers motivate this

## Submission Timeline
| Venue | Estimated Deadline | Best-fit idea |
Table format.

## What to Watch
Specific authors, labs, threads to follow. Name names from the papers.

Rules: every claim traces to a paper. No generic advice. Write for a domain expert."""
