"""initial schema

Revision ID: 86be5c519a58
Revises: 
Create Date: 2026-05-03 19:34:29.690789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '86be5c519a58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('orcid', sa.String(length=64), nullable=True),
    sa.Column('semantic_scholar_id', sa.String(length=64), nullable=True),
    sa.Column('openalex_id', sa.String(length=64), nullable=True),
    sa.Column('affiliations', sa.JSON(), nullable=False),
    sa.Column('social_handles', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('affiliations', sa.JSON(), nullable=False),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('enrichment_status', sa.String(length=32), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index('ix_items_arxiv_id', ['arxiv_id'], unique=False)
        batch_op.create_index('ix_items_doi', ['doi'], unique=True, postgresql_where=sa.text('doi IS NOT NULL'))
        batch_op.create_index('ix_items_enrichment_status', ['enrichment_status'], unique=False)
        batch_op.create_index('ix_items_source_source_id', ['source', 'source_id'], unique=True)

    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index('ix_prompt_versions_agent_version', ['agent_name', 'version'], unique=True)

    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.create_index('ix_raw_items_source_source_id', ['source', 'source_id'], unique=True)

    op.create_table('seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seed_type', sa.String(length=32), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.create_index('ix_seeds_type_identifier', ['seed_type', 'identifier'], unique=True)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('openalex_id', sa.String(length=64), nullable=True),
    sa.Column('venue_type', sa.String(length=64), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_item_id', sa.Integer(), nullable=False),
    sa.Column('cited_item_id', sa.Integer(), nullable=True),
    sa.Column('cited_doi', sa.String(length=256), nullable=True),
    sa.Column('cited_title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cited_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['citing_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_provenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('seed_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('hops', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_provenance')
    op.drop_table('mentions')
    op.drop_table('item_topics')
    op.drop_table('feedback_events')
    op.drop_table('citations')
    op.drop_table('venues')
    op.drop_table('topics')
    with op.batch_alter_table('seeds', schema=None) as batch_op:
        batch_op.drop_index('ix_seeds_type_identifier')

    op.drop_table('seeds')
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_items_source_source_id')

    op.drop_table('raw_items')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_versions_agent_version')

    op.drop_table('prompt_versions')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_source_source_id')
        batch_op.drop_index('ix_items_enrichment_status')
        batch_op.drop_index('ix_items_doi', postgresql_where=sa.text('doi IS NOT NULL'))
        batch_op.drop_index('ix_items_arxiv_id')

    op.drop_table('items')
    op.drop_table('authors')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
