"""Interest profile derivation from seed corpus.

Derives tag affinities, author affinities, and venue affinities
from the items discovered during calibration.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import structlog
import yaml

from packages.seeds.crawl import DiscoveredItem

logger = structlog.get_logger()


def derive_interest_profile(
    items: list[DiscoveredItem],
    output_path: str | Path = "config/interest.yaml",
) -> dict:
    """Derive an interest profile from discovered items.

    Computes tag, author, and venue affinities based on frequency
    and seed proximity (hops). Writes to interest.yaml.
    """
    tag_counter: Counter[str] = Counter()
    author_counter: Counter[str] = Counter()
    venue_counter: Counter[str] = Counter()

    for item in items:
        # Weight by proximity to seed: hop 0 = 1.0, hop 1 = 0.5, hop 2 = 0.25
        weight = 1.0 / (2 ** item.hops) if item.hops >= 0 else 0.1

        for tag in item.tags:
            if tag:
                tag_counter[tag] += weight

        for author in item.authors:
            if author:
                author_counter[author] += weight

        if item.venue:
            venue_counter[item.venue] += weight

    # Normalize to 0-1 range
    tag_affinities = _normalize(tag_counter, top_k=50)
    author_affinities = _normalize(author_counter, top_k=100)
    venue_affinities = _normalize(venue_counter, top_k=30)

    profile = {
        "anchor_embedding": None,  # populated when embedding API is available
        "tag_affinities": tag_affinities,
        "author_affinities": author_affinities,
        "venue_affinities": venue_affinities,
        "relevance_weights": {
            "anchor_distance": 0.35,
            "tag_overlap": 0.20,
            "author_affinity": 0.20,
            "venue_affinity": 0.10,
            "drift": 0.15,
        },
        "drift": {
            "feedback_events": 0,
            "last_updated": None,
        },
        "calibration": {
            "items_count": len(items),
            "unique_tags": len(tag_counter),
            "unique_authors": len(author_counter),
            "unique_venues": len(venue_counter),
        },
    }

    # Write to file
    output_path = Path(output_path)
    with open(output_path, "w") as f:
        f.write("# Atlas interest profile — DERIVED, not hand-edited.\n")
        f.write("# Generated by `atlas calibrate` from seeds.\n")
        f.write("# Manual edits will be overwritten on next calibration.\n\n")
        yaml.dump(profile, f, default_flow_style=False, sort_keys=False)

    logger.info(
        "interest_profile_derived",
        items=len(items),
        tags=len(tag_affinities),
        authors=len(author_affinities),
        venues=len(venue_affinities),
    )

    return profile


def compute_relevance_score(
    item_tags: list[str],
    item_authors: list[str],
    item_venue: str | None,
    profile: dict,
) -> float:
    """Compute relevance score for an item against the interest profile.

    Returns a score between 0 and 1.
    """
    weights = profile.get("relevance_weights", {})
    tag_weight = weights.get("tag_overlap", 0.2)
    author_weight = weights.get("author_affinity", 0.2)
    venue_weight = weights.get("venue_affinity", 0.1)

    # Tag overlap
    tag_affinities = profile.get("tag_affinities", {})
    tag_score = 0.0
    if item_tags and tag_affinities:
        matches = sum(tag_affinities.get(t, 0) for t in item_tags)
        tag_score = min(matches / max(len(item_tags), 1), 1.0)

    # Author affinity
    author_affinities = profile.get("author_affinities", {})
    author_score = 0.0
    if item_authors and author_affinities:
        matches = sum(author_affinities.get(a, 0) for a in item_authors)
        author_score = min(matches / max(len(item_authors), 1), 1.0)

    # Venue affinity
    venue_affinities = profile.get("venue_affinities", {})
    venue_score = 0.0
    if item_venue and venue_affinities:
        venue_score = venue_affinities.get(item_venue, 0)

    # Weighted sum (excluding anchor_distance and drift for now)
    total_weight = tag_weight + author_weight + venue_weight
    if total_weight == 0:
        return 0.0

    score = (
        tag_weight * tag_score
        + author_weight * author_score
        + venue_weight * venue_score
    ) / total_weight

    return round(min(max(score, 0.0), 1.0), 4)


def _normalize(counter: Counter, top_k: int = 50) -> dict[str, float]:
    """Normalize counter values to 0-1 range, keeping top K."""
    if not counter:
        return {}
    most_common = counter.most_common(top_k)
    max_val = most_common[0][1] if most_common else 1.0
    return {k: round(v / max_val, 4) for k, v in most_common}
